version: '3.8'

services:
  # Kontejner za bazu
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mojabaza
    ports:
      - "5433:5432"

  # Tvoj Rust API kontejner
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mojabaza
    depends_on:
      - db